[build]
  functions = "netlify/functions"
  publish = "./"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
package = "netlify-plugin-cloudinary"
inputs = { cloudinary_url = "cloudinary://412726527489346:blOwLP0QhSFaBdbuEA7kEwuR2Lo@dey3ta01p" }