[build]
  functions = "netlify/functions"
  publish = "./"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
  package = "netlify-plugin-image-optim"
  [plugins.inputs]
    quality = 70 
    images = "public/images"  
    debug = true 